# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 兆賢府
description: 純柴燒、陶瓷、老茶、野生普洱
url: http://127.0.0.1

# Build settings
markdown: kramdown
